name: lobe-chat-database
services:
  lobe:
    container_name: lobe-chat
    depends_on:
    - postgresql
    - minio
    - logto
    env_file:
    - .env
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/lobehub/lobe-chat-database:latest
    ports:
    - 3210:3210
    restart: always
  logto:
    container_name: lobe-logto
    depends_on:
      postgresql:
        condition: service_healthy
    entrypoint:
    - sh
    - -c
    - npm run cli db seed -- --swe && npm start
    environment:
    - TRUST_PROXY_HEADER=1
    - DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@postgresql:5432/logto
    - ENDPOINT=https://lobe-auth-api.example.com
    - ADMIN_ENDPOINT=https://lobe-auth-ui.example.com
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/svhd/logto:latest
    ports:
    - 3001:3001
    - 3002:3002
  minio:
    command: 'server /etc/minio/data --address ":9000" --console-address ":9001"

      '
    container_name: lobe-minio
    environment:
    - MINIO_ROOT_USER=YOUR_MINIO_USER
    - MINIO_ROOT_PASSWORD=YOUR_MINIO_PASSWORD
    - MINIO_DOMAIN=lobe-s3-api.example.com
    - MINIO_API_CORS_ALLOW_ORIGIN=https://lobe.example.com
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/minio/minio:latest
    ports:
    - 9000:9000
    - 9001:9001
    restart: always
    volumes:
    - ./s3_data:/etc/minio/data
  postgresql:
    container_name: lobe-postgres
    environment:
    - POSTGRES_DB=lobe
    - POSTGRES_PASSWORD=uWNZugjBqixf8dxC
    healthcheck:
      interval: 5s
      retries: 5
      test:
      - CMD-SHELL
      - pg_isready -U postgres
      timeout: 5s
    image: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/1563457855438522/pgvector/pgvector:pg16
    ports:
    - 5432:5432
    restart: always
    volumes:
    - ./data:/var/lib/postgresql/data
volumes:
  data:
    driver: local
  s3_data:
    driver: local
