Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: 'ECS单机版'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
    ModifyParametersConfig:
      - TemplateName: ECS单机版
        Operation:
          - Name: 变更ECS实例规格
            Description: 变更ECS实例规格
            Type: Custom
            Parameters:
              - EcsInstanceType
          - Name: 变更ECS实例密码
            Description: 变更ECS实例密码
            Type: Custom
            Parameters:
              - InstancePassword
  DeployMetadata:
    SupplierDeployMetadata:
      ArtifactRelation:
        ecs_image_lobe-chat:
          ArtifactId: ${Artifact.EcsImage.ArtifactId}
          ArtifactVersion: draft
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        # 未选择部署地域则采用 []
        AllowedRegions:
          - ap-southeast-1
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  EcsImage:
    ArtifactType: EcsImage
    ArtifactName: ecs_image_lobe-chat
    Description: lobe-chat EcsImage
    SupportRegionIds: 
        - ap-southeast-1
    ArtifactBuildProperty:
      CodeRepo:
        Platform: github
        Owner: JJGGu
        RepoName: JJGGu/lobe-chat
        Branch: main
      RegionId: ap-southeast-1
      CommandType: RunShellScript
      CommandContent: |-
        mkdir -p /root/application
        mkdir -p "/root/application/docker-compose/local/logto"
        if [ -e "/root/code/docker-compose/local/logto/s3_data" ]; then cp -r "/root/code/docker-compose/local/logto/s3_data" "/root/application/docker-compose/local/logto/"; fi
        if [ -e "/root/code/docker-compose/local/logto/.env.example" ]; then cp -r "/root/code/docker-compose/local/logto/.env.example" "/root/application/docker-compose/local/logto/"; fi
        if [ -e "/root/code/docker-compose/local/logto/docker-compose.yml" ]; then cp -r "/root/code/docker-compose/local/logto/docker-compose.yml" "/root/application/docker-compose/local/logto/"; fi
        if [ -e "/root/code/docker-compose/local/logto/data" ]; then cp -r "/root/code/docker-compose/local/logto/data" "/root/application/docker-compose/local/logto/"; fi
        cd /root/application
        cp docker-compose/local/logto/.env.example docker-compose/local/logto/.env
        docker compose -f docker-compose/local/logto/docker-compose.yml build
        docker compose -f docker-compose/local/logto/docker-compose.yml pull || true;