Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: '单机版'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::JJGGu_lobe-chat-docker-compose }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
          - cn-shanghai
          - cn-beijing
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: JJGGu_lobe-chat-docker-compose
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/docker_compose.tar'
  Artifact_2:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-pgvector-pgvector
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_1.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_1.Tag}
      RepoType: Public
  Artifact_3:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-minio-minio
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_2.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_2.Tag}
      RepoType: Public
  Artifact_4:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-svhd-logto
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_3.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_3.Tag}
      RepoType: Public
  Artifact_5:
    ArtifactType: AcrImage
    ArtifactName: AcrImage-lobehub-lobe-chat-database
    ArtifactProperty:
      RepoName: ${AcrImageBuilder.AcrImage_4.RepoName}
      Tag: ${AcrImageBuilder.AcrImage_4.Tag}
      RepoType: Public
AcrImageBuilder:
  AcrImage_1:
    BuildType: DockerRepo
    DockerRepoUrl: pgvector/pgvector:pg16
    RepoName: pgvector/pgvector
    Tag: pg16
  AcrImage_2:
    BuildType: DockerRepo
    DockerRepoUrl: minio/minio
    RepoName: minio/minio
    Tag: latest
  AcrImage_3:
    BuildType: DockerRepo
    DockerRepoUrl: svhd/logto
    RepoName: svhd/logto
    Tag: latest
  AcrImage_4:
    BuildType: DockerRepo
    DockerRepoUrl: lobehub/lobe-chat-database
    RepoName: lobehub/lobe-chat-database
    Tag: latest